// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFácil.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int idCliente { get; set; }

    public string cedula { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string correo { get; set; }

    public string telefono { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();
}