// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFácil.Infraestructura.AccesoDatos;

public partial class DetallePedido
{
    public int idPedido { get; set; }

    public int idProducto { get; set; }

    public int cantidad { get; set; }

    public virtual Pedidos idPedidoNavigation { get; set; }

    public virtual Productos idProductoNavigation { get; set; }
}