// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFácil.Infraestructura.AccesoDatos;

public partial class Distribuidores
{
    public int idDistribuidor { get; set; }

    public string nombre { get; set; }

    public string vehiculo { get; set; }

    public int? idRuta { get; set; }

    public virtual RutasEntrega idRutaNavigation { get; set; }
}