// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFácil.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int idPedido { get; set; }

    public DateTime fecha { get; set; }

    public string estadoEntrega { get; set; }

    public int idCliente { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<RutasEntrega> RutasEntrega { get; set; } = new List<RutasEntrega>();

    public virtual Clientes idClienteNavigation { get; set; }
}