// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFácil.Infraestructura.AccesoDatos;

public partial class RutasEntrega
{
    public int idRuta { get; set; }

    public string origen { get; set; }

    public string destino { get; set; }

    public int? idPedido { get; set; }

    public int tiempoEstimado { get; set; }

    public virtual ICollection<Distribuidores> Distribuidores { get; set; } = new List<Distribuidores>();

    public virtual Pedidos idPedidoNavigation { get; set; }
}